version: '3.8'

services:
  #Backend API
  facebrain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/facebrain-api
#    links:
#      - postgres
#      - redis
    environment:
      POSTGRES_URI: postgres://postgres:Rez5-Kidi@postgres:5432/smart-brain
      REDIS_URI: redis://redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/facebrain-api

  #Postgres
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rez5-Kidi
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"
  #Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
#    command: ["redis-server", "--bind", "redis", "--port", "6380"]

